stage_two: True
norm_corr: True
rend_three_views: True
use_point_renderer: True
inp_pre_pro: False
inp_pre_con: False
feat_ver: 1
img_size: 224
img_patch_size: 14
cvx_up: True
xops: True
rot_ver: 1
st_wpt_loc_inp_no_noise: True
wpt_img_aug: 0.0
img_aug_2: 0.05
